#Dockercompose para levantar una base de datos postgres
version: '3'

services:
  db-contratos:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - contratos-pesca:/var/lib/postgresql/data
    restart:
      always

volumes:
  contratos-pesca:
    external: true



